apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: element
  namespace: matrix
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.global.elementDomain }}
      http:
        paths:
{{- if .Values.element.staticPages.enabled }}
          - path: {{ .Values.element.staticPages.pathPrefix | default "/pages" }}
            pathType: Prefix
            backend:
              service:
                name: element-static
                port:
                  number: {{ .Values.element.staticPages.port | default 80 }}
          - path: {{ .Values.element.staticPages.assetsPathPrefix | default "/static-assets" }}
            pathType: Prefix
            backend:
              service:
                name: element-static
                port:
                  number: {{ .Values.element.staticPages.port | default 80 }}
{{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: element
                port:
                  number: {{ .Values.element.port | default 80 }}
  tls:
    - hosts:
        - {{ .Values.global.elementDomain }}
      secretName: element-tls
