{{- if .Values.matrixrtc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: livekit
  namespace: matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livekit
  template:
    metadata:
      labels:
        app: livekit
    spec:
      enableServiceLinks: false
{{- if .Values.matrixrtc.livekit.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
{{- end }}
      containers:
        - name: livekit
          image: "{{ .Values.matrixrtc.livekit.image.repository }}:{{ .Values.matrixrtc.livekit.image.tag }}"
          imagePullPolicy: {{ .Values.matrixrtc.livekit.image.pullPolicy }}
          args:
            - --config
            - /etc/livekit/config.yaml
          ports:
            - name: http
              containerPort: {{ .Values.matrixrtc.livekit.service.port }}
              protocol: TCP
            - name: rtc-tcp
              containerPort: {{ .Values.matrixrtc.livekit.rtc.tcpPort }}
              protocol: TCP
          volumeMounts:
            - name: livekit-config
              mountPath: /etc/livekit/config.yaml
              subPath: config.yaml
      volumes:
        - name: livekit-config
          configMap:
            name: livekit-config
{{- end }}
