apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/part-of: matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: synapse
  template:
    metadata:
      labels:
        app.kubernetes.io/name: synapse
    spec:
      containers:
        - name: synapse
          image: "{{ .Values.synapse.image.repository }}:{{ .Values.synapse.image.tag }}"
          imagePullPolicy: {{ .Values.synapse.image.pullPolicy }}
          env:
            - name: SYNAPSE_SERVER_NAME
              value: "{{ .Values.global.domain }}"
            - name: SYNAPSE_REPORT_STATS
              value: "yes"
          ports:
            - containerPort: 8008
              name: http
          volumeMounts:
            - name: synapse-data
              mountPath: /data
      volumes:
        - name: synapse-data
          PersistentVolumeClaim:
            claimName: synapse-data
